language: go
go:
  - 1.5
services:
  - redis-server
  - mongodb
  - rabbitmq
before_install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get github.com/coreos/etcd
  - curl -L  https://github.com/coreos/etcd/releases/download/v2.3.1/etcd-v2.3.1-linux-amd64.tar.gz -o etcd-v2.3.1-linux-amd64.tar.gz
  - tar xzvf etcd-v2.3.1-linux-amd64.tar.gz
  - cp etcd-v2.3.1-linux-amd64/etcd $HOME/gopath/bin
install:
  - go get ./... 
before_script:
  - $HOME/gopath/bin/etcd &
  - echo 'CREATE DATABASE PandoCloud' | mysql -uroot
script:
  - cd $HOME/gopath/src/github.com/PandoCloud/pando-cloud/
  - ./unit_test.sh
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
